# Conclusions {#sec-conclusions}

Temporally clustered rainfall events have the potential to cause significant harm to the areas impacted. There is evidence that the rainfall extremes cluster together between 14 and 30 days from the last event in the Hawkesbury River region. This finding is of significance as it suggests the region is more prone to clustered rainfall extremes and the potential resultant river flooding. Further, the clustering of extremes is not significant in either Sydney or Newcastle, the two largest population hubs to the Hawkesbury region, indicating greater resourcing and monitoring is required for the Hawkesbury region once an extreme has occurred than in other parts of NSW.

The use of a Non-Homogeneous Poisson Process to model the intensity and probabilities of the extremes arrival process at each station provides a simple and flexible estimation method that can be adapted to different timescales and used to inform risk management. NHPP models offer an improvement on assuming a constant rate of occurrence for extremes in the Hawkesbury region and makes use of key climate driver information. The NHPP models indicate that easterly winds and low atmospheric pressure drive the extreme arrivals process in the Hawkesbury and that ENSO is the most influential large-scale atmospheric driver on seasonal to annual scales, whilst the impact of ENSO on extreme rainfall events in Sydney and Newcastle is harder to determine.

The key findings of this research are that rainfall extremes are temporally clustered in the Hawkesbury River region, La Niña has an impact on extreme arrivals in the region, and the development of an easily implementable modelling framework for the clustering of extremes.

The tools used to identify and model extreme rainfall events here can be adapted for use at any station in Australia to analyse the temporal clustering behaviour of rainfall extremes. Future directions for this research will focus on improving the models ability to fit the extreme extremes, incorporating the magnitude of events into the clustering model and extending the model into a spatial setting.
