---
bibliography: references.bib
---

# Introduction {#sec-intro}

Extreme rainfall events can be severely harmful to the affected communities, leading to flooding, displacement and financial loss [@bubeck2017]. The negative effects of an extreme rainfall event are heightened when these events cluster within short periods of time [@raymond2020], with the potential to create social and economic problems of an increased magnitude.

The East Coast of Australia is susceptible to temporally clustering extreme rainfall events, caused in part by large-scale climate drivers such as the El Ni単o Southern Oscillation (ENSO) [@delage2020] and localised low pressure systems [@dowdy2019]. This susceptibility has been seen throughout Australian history, with recent examples being the 2020-2022 Eastern Australia floods, and the 2011 Queensland floods. During the 2020-2022 event, a rare 'triple dip' La Ni単a occurred, whilst the 2011 floods featured one of the strongest La Ni単a events on record.

Extreme rainfall is driven by prevailing large-scale atmospheric drivers, localised synoptic patterns and the interplay between these large-scale and local drivers. The phase and strength of ENSO dictates rainfall variability in Eastern Australia, with a La Ni単a phase typically bearing lower temperatures and more rainfall [@santoso2019]. The Indian Ocean Dipole (IOD), a sea surface temperature (SST) anomaly in the Indian Ocean, also impacts rainfall variability across Australia, however is less relevant east of the Great Dividing Range [@pepler2014]. Extreme rainfall east of the Great Dividing Range is generally attributable to maritime low pressure systems known as East Coast Lows (ECL), characterised by heavy rainfall and strong winds [@speer2009]. When winds are easterly, these systems have a tendency to remain stationary over an area, resulting in greater rainfall totals, increasing the likelihood of an extreme event occurring [@pepler2014a].

Concern around climate change and its impact on large-scale and localised atmospheric drivers is an ongoing field of research [@cai2023; @yeh2022; @king2023], however the frequency and severity of extreme weather events is expected to increase as anthropogenic warming continues [@huber2011]. The combination of future climate related concerns and a pre-existing susceptibility to weather extremes has created the need for statistical models that can quantify risks associated with these events.

To determine what constitutes an extreme, the Peak Over Threshold (POT) method [@coles2001] is a unifying feature of the literature. Following threshold selection, which is a contextual process, the current literature uses point processes to analyse compounding extreme weather events [@bevacqua2021; @mailier2006], with applications focused on Europe and North America. Literature using point processes typically use a homogeneous point process with a constant intensity parameter [@villarini2011] as a baseline, then model time-varying intensity using a non-homogeneous point process [@vitolo2009] to better reflect the seasonality and impact of climate drivers on the extreme event arrival process.

Recent innovations have used Generalised Additive Models (GAM) to model seasonality as a smooth cyclic function of time [@barton2022], analysing the impact that various weather regimes have on the temporal clustering of extreme rainfall events in Europe. Alternative approaches in the literature use different point process methods such as Cox models to capture hazard rates [@villarini2013] and Ripley's K Function to determine the statistical significance of the temporal clustering of extremes [@tuel2021].

This paper uses a combination of simulation-based methods to detect the presence of temporal clustering [@barton2016] and Non-Homogeneous Poisson Processes (NHPP) to model the time-varying intensity of the extreme arrivals process. NHPPs have been used throughout the literature to model both the counts and arrivals of extreme events [@villarini2012]. These models are suitable for modelling the temporal clustering of rainfall extremes as they are simple, interpretable, and allow for the intensity to be a function of time and covariates. Interpretability is a key benefit to the use of a NHPP model as opposed to a GAM, as covariates are linearly interpretable. However, a NHPP model imposes a more restrictive framework due to their inability to capture the complex non-linear relationships that GAMs are able to.

Atmospheric drivers have differing timescales and sources of predictability [@meehl2021], therefore this paper proposes a set of NHPP models that are timescale flexible. Given the recent and historical flooding events in the region, the above methods are adapted to analyse the temporal clustering of extreme rainfall events in the Hawkesbury River region.

This research provides novel insights into the temporal clustering of extreme rainfall events in an Australian context. These insights are provided through quantifying the statistical significance of the clustering, the impact of climate drivers and the use of NHPP models to estimate the probability of clustered events occurring across timescales. The methods adopted can be generalised to weather stations across Australia with station-specific covariate information. The findings of this research can be used to inform disaster management and policy [@lala2021], in hope of mitigating the social and economic costs of temporally compounding extreme weather events.

This paper is structured as follows: @sec-data contains details about the data used in this paper. @sec-methods explains the methodology behind the simulation-based testing of significance for clustering and climate drivers, and the methodology behind the NHPP models capturing the probability of compounding events. @sec-eda comprises of exploratory data analysis for each station of interest. @sec-results and @sec-discussion provide the results and discussion of this paper, and @sec-conclusions presents the conclusions and considers future research directions.
